<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Duels</AssemblyName>
    <RootNamespace>Duels</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.374" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <Reference Include="MenuManagerApi">
      <HintPath>..\MenuManagerApi\MenuManagerApi.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
